# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stu_id', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=1000)),
                ('grilled', models.CharField(max_length=200)),
                ('task', models.BooleanField(default=False)),
            ],
        ),
    ]
