# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-11 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruit',
            old_name='stu_id',
            new_name='student_id',
        ),
    ]
