# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-11 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_auto_20170811_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='task',
            field=models.CharField(max_length=200),
        ),
    ]
