# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_auto_20170811_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=1000)),
                ('grilled_by', models.CharField(max_length=200)),
                ('task', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='grilled',
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='task',
        ),
        migrations.AddField(
            model_name='member',
            name='recruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Recruit'),
        ),
    ]
