# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0005_auto_20170812_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='recruit',
        ),
        migrations.AddField(
            model_name='member',
            name='recruit_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.Recruit'),
        ),
    ]
