# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0006_auto_20170812_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='recruit_name',
            new_name='recruit',
        ),
    ]
