# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0007_auto_20170812_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='contact_no',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
