# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0008_recruit_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='task_status',
            field=models.BooleanField(default=False),
        ),
    ]
